OPENAI_API_KEY = "e83a3572341642228cd2fbd04b0b2da7"

[connections.snowflake]
user = "Jin"
password = "Bsci@1234"
#authenticator="EXTERNALBROWSER"
warehouse = "EDH_COMM_DATA_LAKE_EMA_CHATBOT_WH"
role = "EDH_COMM_DATA_LAKE_EMA_CHATBOT"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "bscai"